#!/bin/bash
#
# @file
# Configuration

##
 # File path to the php you want to use for compiling
 #
#php = '/Applications/MAMP/bin/php/php5.3.14/bin/php'
php = $(which php)

##
 # The drupal credentials for a user who can access any iframe content
 #
credentials = "http://user:pass@www.my-site.com/user/login";

##
 # The name of the drupal module to build advanced help output for.
 #
drupal_module = 'my_module';
